export const LOAD_PRODUCTS_REQUEST = 'LOAD_PRODUCTS_REQUEST';
export const LOAD_PRODUCTS_SUCCESS = 'LOAD_PRODUCTS_SUCCESS';
export const LOAD_PRODUCTS_FAILURE = 'LOAD_PRODUCTS_FAILURE';

export const LOAD_ONE_PRODUCT_REQUEST = "LOAD_ONE_PRODUCT_REQUEST";
export const LOAD_ONE_PRODUCT_SUCCESS = "LOAD_ONE_PRODUCT_SUCCESS";
export const LOAD_ONE_PRODUCT_FAILURE = "LOAD_ONE_PRODUCT_FAILURE";
